from pydantic import BaseModel, Field

class TaskRequest(BaseModel):
    task_id: str = Field(..., description="Unique identifier for the task.")
    prompt: str = Field(..., description="The instruction or query for the AI agent.")
    
class TaskResponse(BaseModel):
    task_id: str = Field(..., description="Unique identifier for the task.")
    status: str = Field(..., description="Status of the task (e.g., 'completed', 'failed').")
    result: str = Field(..., description="The response generated by the AI agent.")
